name: Build & Publish a Docker image

on:
  push:
    branches: ["master"]

jobs:
  build-and-publish:
    uses: trusted/shared-workflows/.github/workflows/build_and_push_dockerfile.yml@main
    with:
      image_name: url-to-pdf-api
